airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
]

flights/urls.py
from django.urls import path
from . import views

app_name = "flights"
urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

flights/models.py
from django.db import models

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return(f"{self.city} ({self.code})")


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def is_valid_flight(self):
        return (self.origin != self.destination and self.duration > 0)

    def __str__(self):
        return(f"{self.id}: from {self.origin} to {self.destination}")

class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return(f"{self.first} {self.last}")

flights/views.py
from django.shortcuts import render, redirect
from .models import *
from django.urls import reverse
from django.http import Http404

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    try:
        flight = Flight.objects.get(id=flight_id)
    except Flight.DoesNotExist:
        raise Http404("Flight not found.")

    return render(request, "flights/flight.html",{
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers":Passenger.objects.exclude(flights=flight).all()
    })

def book(request, flight_id):
    # with method POST transfer variables flight.id(from header) and passenger_id(from form)
    if request.method == "POST":
        #flight = Flight.objects.filter(id = flight_id).first()  #is the same with next
        flight = Flight.objects.get(pk=flight_id) #pk is PrimaryKey shortcut
        passenger = Passenger.objects.get(pk=int(request.POST["passenger_id"]))
        passenger.flights.add(flight)
        return redirect(reverse("flights:flight", args=(flight.id,)))

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flight {{flight.id}}</h1>
<ul>
	<li>Origin: {{flight.origin}}</li>
	<li>Destination: {{flight.destination}}</li>
	<li>Duration: {{flight.duration}}</li>
</ul>

<h2>Passengers:</h2>
<ul>
	{% for passenger in passengers %}
	<li>{{passenger}}</li>
	{% empty %}
	<li>No passengers</li>
	{% endfor %}
</ul>

<h2>Add passenger</h2>
<form action="{% url 'flights:book' flight.id %}" method="POST">
	{% csrf_token %}
	<select name="passenger_id">
		{% for passenger in non_passengers %}
		<option value="{{ passenger.id }}">{{ passenger }}</option>
		{% endfor%}
	</select>
	<input type="submit">
</form>



<a href="{% url 'flights:index' %}">All flights</a>

{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flights</h1>
{% for flight in flights %}
<li>
	<a href="{% url 'flights:flight' flight.id %}">
		Flight #{{ flight.id }}
	</a>
	from {{flight.origin}}  to {{flight.destination}}, duration {{flight.duration}} min.
</li>
{% endfor %}
{% endblock %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>
		Flight
	</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>